export const GET_BOOKMARKED_DATA_REQUEST = 'GET_BOOKMARKED_DATA_REQUEST';
export const GET_BOOKMARKED_DATA_SUCCESS = 'GET_BOOKMARKED_DATA_SUCESS';
export const GET_BOOKMARKED_DATA_FAILURE = 'GET_BOOKMARKED_DATA_FAILURE';